class PlotLine:
    Samplingfrequency=0
    MaxFrequency=0
    Frequency=0
    magnitude=0
    phase = 0
    data=None
    signal = None
    name = ""
    pen = None
    data_line = None
    SamplingInterval=0
    sampledSignal=None
    signaltime=None
    signaltype=0
    isloaded=0
    sampledSignalTime=None
    sampledSignalAmplitude=None
    num_samples=0
    errorGraph=None
    reconstructed_signal=[]
    isDat = 0